pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Android-Clean-Architecture-Sample"
include ':app'
include ':shared'
include ':core:model'
include ':core:designsystem'
include ':core:testing'
include ':core:domain'
include ':core:data'
include ':feature:characters'
include ':feature:episodes'
include ':feature:locations'
