plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace = 'com.example.rickymortydn'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId = "com.example.rickymortydn"
        minSdk {
            version = release(30)
        }
        targetSdk {
            version = release(36)
        }
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation project(':core:data')
    implementation project(':core:domain')

    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.ui
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    debugImplementation libs.androidx.compose.ui.tooling
}
