config:
  validation: true

naming:
  FunctionNaming:
    excludes:
      - '**/src/commonTest/**'
      - '**/src/androidDeviceTest/**'
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    excludes:
      - '**/ui/theme/**'
      - '**/*Screen.kt'
      - '**/src/test/**'
      - '**/src/androidTest/**'
      - '**/src/commonTest/**'
      - '**/src/androidDeviceTest/**'
  UnusedPrivateMember:
    ignoreAnnotated:
      - Preview
